### PR TITLE
feat: added issue btns and respective forms

### PR DESCRIPTION
**Pull request by dakshsinghrathore**
I solved the issue #30 , kindly review it and merge.

### CODE REVIEW

**Comment by 1Shubham7** [comment]
Please share ss for the before and after changes

**Comment by dakshsinghrathore** [comment]
> Please share ss for the before and after changes

The changes will be visible once you merge the PR, but you can have a glimpse of it here #30

**Review by 1Shubham7 — APPROVED** [review]
LGTM

**Comment by dakshsinghrathore** [comment]
@1Shubham7  kindly add apt gssoc labels

**Pull request merged**
