### PR TITLE
docs: enhance docs 

### PR DESCRIPTION
**Pull request by SrNightmare09**
- improve installation guide
- improve contribution guidelines
- add preview image
- add technology badges

### CODE REVIEW

**Comment by SrNightmare09** [comment]
I would also like to recommend that we should remove the about section of the readme as the information about the website is already provided below the main heading.

**Comment by SrNightmare09** [comment]
The latest commit removes the additional underline when you hover over a link

| Before | After |
| --- | --- |
| image | image |

**Comment by 1Shubham7** [comment]
Thanks @SrNightmare09  for contributing but please make one change per PR, otherwise I will have to merge the entire PR. I can't merge this since the underline in the "GitHub" text is intentional. Can you make another PR making change in just docs.

**Comment by 1Shubham7** [comment]
@SrNightmare09 The best way to get PRs merged is to make small PRs with small changes so that I can roll back rather than 1 big PR with 5-6 commits. Also do one thing in one PR. If PR is about docs only do docs. For any other additions, you can open another PR.

**Comment by SrNightmare09** [comment]
@1Shubham7 I have made the changes and reverted to only change in documentation.

**Comment by 1Shubham7** [comment]
@SrNightmare09  I told you the underline looks good. It is intentional. Please make PR for the other commits where you change the readme doc.

**Comment by SrNightmare09** [comment]
> @SrNightmare09  I told you the underline looks good. It is intentional. Please make PR for the other commits where you change the readme doc.

I have removed the changes to the css files, so the underline is still visible. I don't seem to understand what else you want from me.

**Comment by 1Shubham7** [comment]
@SrNightmare09 Its perfect now!! I am really sorry if this was annoying but mostly in open-source one should only do in the PR what he/she was assigned in the issue and make small PRs.

**Comment by 1Shubham7** [comment]
Thank you @SrNightmare09 for your time. Please contribute more. I really value your contributions.

**Pull request merged**
