### PR TITLE
Website Logo has been resolved KIndly check it 

### PR DESCRIPTION
**Pull request by Damini2004**
As the issue was to design the logo.
I have designed the logo , so kindly go through it.
Here by im attaching more logo picture if any of you like it we can replace it.
logo
logo2

### CODE REVIEW

**Comment by 1Shubham7** [comment]
Logos are not good... please create logos on figma and share figma file.

**Review by 1Shubham7 — CHANGES_REQUESTED** [review]
Logos are not good... please create logos on figma and share figma file.

**Comment by Damini2004** [comment]
Here can share the figma file so i am previewing the logo in png file. KIndly go through it and suggest your changes.

**Comment by 1Shubham7** [comment]
I didn't get what you said. please share the figma file link.

**Comment by Damini2004** [comment]
https://www.figma.com/design/dj2ujMVEbEnisQXNgKOdWg/LOGO?node-id=3%3A3&t=1murT6eOygMTwd6P-1  
Here is the link of logo figma file

**Comment by 1Shubham7** [comment]
Logo is really basic, please don't just try getting your PRs merged, try to learn stuff that is more important. Please give some time to logo (you can't do it in 10mins) watch a course on YT. please come up with  a good logo or else I will have to close the PR.

**Comment by Damini2004** [comment]
https://www.canva.com/design/DAF9KKQHw60/8pZeuTz1URhFGc5WORQvqw/edit?utm_content=DAF9KKQHw60&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

I am highly Proficient in CANVA instead of FIGMA, so i designed in canva.
Here i design some logo kindly go through

**Review by 1Shubham7 — CHANGES_REQUESTED** [review]
Your logos don't look good. I was something fun, its a fun project.

**Comment by 1Shubham7** [comment]
Please attempt other Isssues. I think we should close this... really sorry.

**Pull request closed without merging**
