### PR TITLE
Enhanced : adding some badges to the readme to make it look more visually appealing #26

### PR DESCRIPTION
**Pull request by Santhosh-Siddhardha**
**Changes made** 
- Added owner badge , linked it to the owner and aligned it to the center.
- Aligned the technology badges to center to make it look more visually appealing.
- Added Nodejs badge and linked it to official Nodejs website.
- Added License section which contains License badge that links to LICENSE.

### CODE REVIEW

**Comment by 1Shubham7** [comment]
Please share the SS for the changes you made. It is tough to evaluate otherwise...

**Review by 1Shubham7 — CHANGES_REQUESTED** [review]
Please share the SS for the changes you made. It is tough to evaluate otherwise...

**Comment by Santhosh-Siddhardha** [comment]
@1Shubham7 These are the changes I made
- Added owner badge , linked it to the owner and aligned it to the center.
- Aligned the technology badges to center to make it look more visually appealing.

Screenshot 2024-05-10 204727
- Added Nodejs badge and linked it to official Nodejs website.

Screenshot 2024-05-10 204841
- Added License section which contains License badge that links to LICENSE.

Screenshot 2024-05-10 204926

**Comment by Santhosh-Siddhardha** [comment]
Could you please mention the gssoc label and level label for this
contribution.
It will be helpful to my points

**Comment by 1Shubham7** [comment]
I am not sure about if I have to add the label in PR as well. Please remind me later, I will ask the GSSoC people. (Or you can show me a PR example from any other project in GSSoC.

**Comment by Santhosh-Siddhardha** [comment]
I asked this question in discord and One of the GSSoC people gave this
reply,
[image: image.png]
So you can add the label, since you are project Admin

**Comment by Santhosh-Siddhardha** [comment]
@1Shubham7 Please add the labels for PR also

**Comment by Santhosh-Siddhardha** [comment]
@1Shubham7 Please add gssoc and level label, otherwise they will not consider my points

**Comment by Santhosh-Siddhardha** [comment]
@1Shubham7 Thank you but label should be level2, there should not be any capitals and spaces. Then only they will consider

**Comment by Santhosh-Siddhardha** [comment]
@1Shubham7 Please add gssoc label and please assign this PR to me

**Pull request merged**
